# Generated by Django 5.2.7 on 2025-10-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDoacao',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=16)),
                ('rua', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_func', models.CharField(max_length=14, unique=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao_sangue.centrodoacao')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doacao_sangue.funcionario')),
                ('coren', models.CharField(max_length=8, unique=True)),
            ],
            bases=('doacao_sangue.funcionario',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doacao_sangue.funcionario')),
                ('crm', models.CharField(max_length=8, unique=True)),
            ],
            bases=('doacao_sangue.funcionario',),
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao_sangue.doador')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao_sangue.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estoque', models.CharField(max_length=3)),
                ('quantidade', models.PositiveIntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='doacao_sangue.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='centrodoacao',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_doacao', to='doacao_sangue.hospital'),
        ),
        migrations.CreateModel(
            name='Sangue',
            fields=[
                ('id_sangue', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=2)),
                ('fator_rh', models.CharField(max_length=1)),
                ('sangue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doacao_sangue.atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_total', models.BooleanField(blank=True, null=True)),
                ('exame_aids', models.BooleanField(blank=True, null=True)),
                ('exame_sifilis', models.BooleanField(blank=True, null=True)),
                ('exame_hepatite_a', models.BooleanField(blank=True, null=True)),
                ('exame_hepatite_b', models.BooleanField(blank=True, null=True)),
                ('sangue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doacao_sangue.sangue')),
            ],
        ),
    ]
